displayName: Throttle
type: middleware

import: github.com/joegarb/traefik-throttle

summary: Limit concurrent requests routed to services by delaying (rather than rejecting) requests over the limit. Useful for underpowered servers in very low-traffic environments (ie. homelabs).

testData:
  maxRequests: 10
  maxQueue: 100
  maxWait: 5s
  verbose: false
  spacing: 0s
